### ISSUE TITLE
Refine language grammar and key words

### ISSUE THREAD

**Issue by mirdaki** [mirdaki/theforce#13]
Though the language works, some things could probably be improved or changed. We should do the things we know now before we start versioning things (#4). Working list:
- [x] The True and false quotes should either both be the full quotes or just partial ones #28 
- [x] Reading values is finicky #27 
- [X] Variable types can change at any point, consider restricting that or streamlining process #23 
- [X] Decide if replacing an existing variable is possible #23 
- [ ] Consider making true and false values print the quotes, instead of just true or false
- [x] Consider swapping and and or #28 
- [x] Consider making not void a void keyword instead #28 
- ~[ ] Check function returns for edge cases~
- [x] General look through of operations and statement combinations to see if some might be better suited together (for instance, matching a Yoda quote with a Yoda quote) #28
